name: Scrape latest schema

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 */1 * *'

jobs:
  schema:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.commit.outputs.changed }}
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install deps
      run: npm ci
    - name: Scrape schema
      run: npm run gen-schema
    - name: Commit and push schema
      id: commit
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add schema.graphql schema.json
        timestamp=$(date -u)
        # If nothing happened changed, we stop at the next line
        git commit -m "Latest schema: ${timestamp}" || echo "changed=false" >> $GITHUB_OUTPUT && exit 0
        git push
        echo "changed=true" >> $GITHUB_OUTPUT
  create-docs:
    runs-on: ubuntu-latest
    needs: schema
    if: "${{ needs.schema.outputs.changed == 'true' }}"
    steps:
      - name: Check out this repo
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Build docs
        run: npm gen-docs
      - name: Push docs
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/"
  deploy:
    # Add a dependency to the build job
    needs: create-docs

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
